### ISSUE TITLE
add config param to rmd files

### ISSUE THREAD

**Issue by brianFSM** [PriyamPatel-Northwestern/scRNA-Seq#45]
Add a parameter to the header of the rmd files so that we can pass the name of a config file when rendering.

```
---
output:
  html_document:
    pandoc_args: './common.yaml'
params:
  config.args: "./config.yaml"
---
```

Then

`config.args <- read_yaml(params$config.args)`
